[back-to-doc](../../MED5018-FinalProject.md)

- ### [Direction 1: 疫苗 vs new cases & new deaths](https://github.com/Ally-Vella/MED5018-project/tree/master/code/direction1)
	- @ZhengLihao1004
	- [hospitalize](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-hospitalizations.md) 收治 上呼吸机 （候选
- aim
	- 疫苗对病毒抗性和感染的作用
- data input
	- vaccination
		- [table-vaccinations.md](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-vaccinations.md)
		- [table-vaccination-access.md](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-vaccination-access.md)
		- [table-vaccination-search-insights.md](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-vaccination-search-insights.md)
	- new cases and deaths
		- [table-epidemiology.md](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-epidemiology.md)
	-
- analysis
	- correlations
	- distribution
		- 如果有疫苗接种数量随时间的数据 -> 疫苗接种的 和 生病的
	- 接种率高于 xx% v.s. 接种率低于 yy% 时，cases & deaths （对不同疫苗）
- visualization